d3b-center/OpenPedCan-manuscript

.github/ISSUE_TEMPLATE/propose-updates-to-manuscript.md
.github/PULL_REQUEST_TEMPLATE.md

@jharenza, I have added `tickets` and `pull requests` templates copied from the OpenPBTA-manuscript repo.

add ticket and PR templates

---

content/06.methods.md

Added independent sample selection methods to `content/06.methods.md`.
- #9 
The added independent sample selection methods in `content/06.methods.md`.
Yes.
- [NA] All citations follow the [Manubot citation instructions](https://github.com/d3b-center/OpenPedCan-methods/blob/master/USAGE.md#citations)
- [NA] All changes or additions to tables follow the [Manubot table instructions](https://github.com/d3b-center/OpenPedCan-methods/blob/master/USAGE.md#tables)
- [NA] All figures follow the [Manubot figure instructions](https://github.com/d3b-center/OpenPedCan-methods/blob/master/USAGE.md#figures)
Edit the file in …

Add independent sample selection methods

---

content/06.methods.md

Added methods for focal-cn-file-preparation, including updated methods to resolve duplicate gene status calls with were implemented in [PR #292](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/292). 
[Ticket #8](https://github.com/d3b-center/OpenPedCan-methods/issues/8)
Let me know if more detail is needed on how duplicate calls were resolved--I briefly describe in text and reference the analysis module which gives more detailed description in the README
Right now I am citing the OpenPBTA manuscript for much of these methods since they are unchanged. If more detail is needed on any module components, please let me know. 
Yes
Unless otherwise noted above, this PR will be considered …

add focal-cn-methods

---

content/metadata.yaml

Adding author to metadata
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv …
```

Adding author: Saksham Phul

---

content/metadata.yaml

```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> …
```

Add Alex Sickler to authors

---

content/06.methods.md

Include rnaseq summary stats methods
- https://github.com/d3b-center/OpenPedCan-methods/issues/28
Description of the method
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 …
```

rnaseq summary stats methods

---

content/metadata.yaml

Add author information for Sangeeta Shukla to be included in the manuscript
[OPC-methods Issue 31](https://github.com/d3b-center/OpenPedCan-methods/issues/31)
Please let me know if any other information is needed.
No
Yes
```
(( len = …
```

Add manuscript author info for Sangeeta Shukla

---

content/06.methods.md

Add IHG, ATRT, and neuroblastoma subtyping in the method section.
https://github.com/d3b-center/OpenPedCan-methods/issues/16
Citations
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc …
```

Updated manuscript: Add IHG, ATRT, and neuroblastoma subtyping

---

content/06.methods.md

Describe the D3b GATK pipeline methods used to generate the seg file used in the OPenPedCan [copy_number_consensus_call](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/copy_number_consensus_call) module to call consensus CNVs alongside CNVkit, and ControlFREEC.
https://github.com/d3b-center/OpenPedCan-methods/issues/4
Method, Consensus CNV Calling (citation and parameter) …

Add consensus CNV calling in method section

---

content/06.methods.md

Update methods to include SNV consensus analyses
A description of the D3b somatic mutation calling pipeline used to call SNVs and indels and how they are used to generate the OPenPedCan consensus SNV calls.
https://github.com/d3b-center/OpenPedCan-methods/issues/5
method, consensus SNV calling (citation)
Yes
However, if you want to update the first line to have an accurate count of words and you want to remove …

Update methods to include SNV consensus analyses

---

content/metadata.yaml

Add author YZ.
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

Add author YZ

---

content/metadata.yaml

Per email, adding:
```
- github: taylordm
name: Deanne Taylor
initials: DT
orcid: 0000-0002-3302-4610
email: taylordm@chop.edu
contributions:
- Conceptualization
- Data curation
- Formal analysis
- Funding acquisition
- Investigation
- Methodology
- Software
- Supervision
- Writing – Original draft
- Writing - Review and editing
affiliations:
- Department of Bioinformatics and Health Informatics, Children's Hospital of Philadelphia, Philadelphia, PA, 19104, USA
- Department of Pediatrics, University of Pennsylvania Perelman Medical School, Philadelphia, PA, 19104, USA
```
https://github.com/d3b-center/OpenPedCan-methods/issues/31
Unless otherwise noted above, this PR will be considered ready for review when all four items have been …

add deanne as author

---

content/metadata.yaml

Adds @afarrel to author list
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv …
```

add alvin to author list

---

content/metadata.yaml

[Issue#31](https://github.com/d3b-center/OpenPedCan-methods/issues/31)
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en …
```

Adding Aditya Lahiri as author

---

content/06.methods.md

I rearranged and made some deletions in this PR
NA
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt …
```

cleanup on some remaining columns, rearrange some text

---

content/06.methods.md

Added brief `fusion_filtering` module description to methods
No issue
Is the description accurate and does the link work correctly?
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc …
```

Added fusion_filtering module description to methods

---

content/metadata.yaml

Add Zhuangzhuang Geng to author list 
https://github.com/d3b-center/OpenPedCan-methods/issues/31
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; …
```

Add Zhuangzhuang to author list

---

content/metadata.yaml

Adding myself to the list of authors.
#31 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

Adding Matthew Lueder to the author list

---

content/02.introduction.md

Update the introduction section for the OpenPedCan project
Reviewed CAVATICA and OpenPedCan git repo introduction and added content here.
[OPC-methods Issue 48](https://github.com/d3b-center/OpenPedCan-methods/issues/48)
Please share your thoughts on the overall content.
No
Yes
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your …

Updated intro section

---

.github/workflows/manubot.yaml

Fixing Github actions permissions for Manubot
https://github.com/d3b-center/OpenPedCan-methods/issues/53
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > …
```

Adding manubot privs

---

content/06.methods.md

splicing method

---

.github/workflows/manubot.yaml
build/build.sh
build/environment.yml

Pull over latest build shell script from OpenPBTA 
Attempts to close #61 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv …
```

pull build from OpenPBTA ms

---

content/06.methods.md

Closed this by accident 
Closes #66 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

Cnv tumor only methods

---

content/06.methods.md

This PR adds miRNA methods per https://docs.google.com/document/d/1pCrKHJdts42C7VBKpUgr8P_hOmde7fBtHbSjw_-Fzmw/edit
Closes #58 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 …
```

add miRNA methods

---

content/metadata.yaml

This PR updates the yaml file per the PR [here](https://github.com/d3b-center/OpenPedCan-analysis/pull/573), which pins first 3 authors and scrambles then based on code contributions then non code contributions. 
Need to also add other noncode authors, but will do in a separate PR.
Closes #84 
Note: I had to add Rocky (who may or may not want to be added, TBD, trying to contact) and Tonia to the yaml manually, so it does not exactly match what is in OPC analysis. I inserted them based on where they should go from the code run. Added Joe and Ammar at the end, and they will get randomized next trigger.
Edit the file in …

Author order based on contributions

---

content/metadata.yaml

This PR adds John Maris and Sarah Tasian, who were co-PIs/co-Is, and goes through all contributions to update based on those to OPC, not MTP as a whole, since the scope of this is OPC only.
```
(( len = $(awk '!a[$0]++' < …
```

add JMM, ST, update contributions based on OPC, not MTP

---

build/assets/custom-dictionary.txt
content/03.Data_Description_Methods.md

Closes #92. This PR adds updated methods describing mutational signatures analyses in OpenPedCan
#92 
Please review new text. 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo …
```

Add updated mutsigs methods

---

build/assets/custom-dictionary.txt
content/00.Title_page.md
content/06.administrative.md
content/metadata.yaml

Adds more authors, removes Rocky due to no contact, moves Rocky and Rust to acknowledgements. Stephanie prefers to use Stefankiewicz.
Closes #97 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; …
```

add methylation/mionco authors

---

content/03.Data_Description_Methods.md

Made updates to molecular-subtyping headers so they are consistent
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 …
```

Fix subtyping headers

---

content/03.Data_Description_Methods.md

Small suggestions, feel free to reject this if they don't make sense.
Add (CHOP) after Children's Hospital...
Combine sections that refer to previous manuscript.
```
(( len = $(awk '!a[$0]++' < …
```

combine sections that refer to the previous manuscript

---

build/assets/custom-dictionary.txt
content/03.Data_Description_Methods.md
content/04.Availability_of_source_code_and_requirements.md
content/08.supplemental.md

Closes #108 
Closes #107 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

add supp tables, sections for validation and reuse

---

build/assets/custom-dictionary.txt
content/01.Abstract.md
content/03.Data_Description_Methods.md
content/04.Availability_of_source_code_and_requirements.md
content/06.administrative.md
content/08.supplemental.md
content/metadata.yaml

Closes #111. This PR updates methods section to include criteria used to classify MB, SHH subtype tumors into subgroups (alpha, beta, gamma, delta). 
#111 
Please review new text and ensure it matches [the criteria](https://github.com/d3b-center/OpenPedCan-analysis/pull/565) used to classify MB SHH tumors. 
No
Yes
- [] All citations follow the [Manubot citation instructions](https://github.com/d3b-center/OpenPedCan-methods/blob/master/USAGE.md#citations)
You do not need to change …

add MB SHH subtyping methods
